services:
  titan:
    image: titan-titan
    restart: always
    depends_on:
      - bitcoind
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:3030:3030
    entrypoint: /home/titan/titan
    environment:
      - RUST_BACKTRACE=full
    networks:
      titan-network:
        ipv4_address: 172.28.0.2
    command: |
      --data-dir=/home/titan/data
      --chain=regtest
      --bitcoin-rpc-url=http://172.28.0.1:18443
      --bitcoin-rpc-username=bitcoin
      --bitcoin-rpc-password=bitcoinpass
      --tcp-address=0.0.0.0:8080
      --enable-tcp-subscriptions
    volumes:
      # make sure titan_data is owned by userid 1000!
      # run: sudo chown -R 1000:1000 ./titan_data
      - "./titan_data:/home/titan/data"
      - "./btcd_data:/var/lib/bitcoin-core"

  bitcoind:
    image: bitcoin/bitcoin
    ports:
      - 0.0.0.0:18443:18443
    volumes:
      - "./btcd_data:/var/lib/bitcoin-core"
    environment:
      - BITCOIN_DATA=/var/lib/bitcoin-core
    networks:
      titan-network:
        ipv4_address: 172.28.0.3
    command: |
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -datadir=/var/lib/bitcoin-core
      -rpcbind=bitcoind
      -printtoconsole
      -rpcauth=bitcoin:fdd4aa9e420497f24745c7f06d9f2661$26322984e7d07e2e40b8df79dce78eabe8c891c956a10a3e6ceaac7df4cfa9cb
      -fallbackfee=0.00000001

networks:
  titan-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
