services:
  titan:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      bitcoind:
        condition: service_healthy
    ports:
      - 0.0.0.0:${TITAN_TCP_PORT:-8080}:${TITAN_TCP_PORT:-8080}
      - 0.0.0.0:${TITAN_HTTP_PORT:-3030}:${TITAN_HTTP_PORT:-3030}
    networks:
      titan-network:
        ipv4_address: 172.28.0.2
    environment:
      - COMMIT_INTERVAL=${COMMIT_INTERVAL:-5}
      - BITCOIN_RPC_URL=http://bitcoind:${BITCOIN_RPC_PORT:-18443}
      - BITCOIN_RPC_USERNAME=${BITCOIN_RPC_USERNAME:-bitcoin}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-bitcoinpass}
      - CHAIN=${BITCOIN_NETWORK:-regtest}
      - HTTP_LISTEN=0.0.0.0:${TITAN_HTTP_PORT:-3030}
      - TCP_ADDRESS=0.0.0.0:${TITAN_TCP_PORT:-8080}
    volumes:
      - "titan-data:/home/titan/data"

  bitcoind:
    image: bitcoin/bitcoin
    ports:
      - 0.0.0.0:${BITCOIN_RPC_PORT:-18443}:${BITCOIN_RPC_PORT:-18443}
    volumes:
      - "btcd-data:/var/lib/bitcoin-core"
    networks:
      titan-network:
        ipv4_address: 172.28.0.3
    command: |
      -${BITCOIN_NETWORK:-regtest}
      -rpcallowip=0.0.0.0/0
      -datadir=/var/lib/bitcoin-core
      -rpcbind=bitcoind
      -rpcuser=${BITCOIN_RPC_USERNAME:-bitcoin}
      -rpcpassword=${BITCOIN_RPC_PASSWORD:-bitcoinpass}
      -fallbackfee=0.00000001
      -txindex
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-${BITCOIN_NETWORK:-regtest}",
          "-rpcconnect=bitcoind",
          "-rpcport=${BITCOIN_RPC_PORT:-18443}",
          "-rpcuser=${BITCOIN_RPC_USERNAME:-bitcoin}",
          "-rpcpassword=${BITCOIN_RPC_PASSWORD:-bitcoinpass}",
          "getblockchaininfo",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  titan-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  titan-data:
  btcd-data: 