version: "3.8"

services:
  titan:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      bitcoind:
        condition: service_healthy
    ports:
      - 0.0.0.0:${TITAN_TCP_PORT}:${TITAN_TCP_PORT}
      - 0.0.0.0:${TITAN_HTTP_PORT}:${TITAN_HTTP_PORT}
    networks:
      titan-network:
        ipv4_address: 172.28.0.2
    environment:
      - COMMIT_INTERVAL=${COMMIT_INTERVAL}
      - BITCOIN_RPC_URL=http://bitcoind:${BITCOIN_RPC_PORT}
      - BITCOIN_RPC_USERNAME=${BITCOIN_RPC_USERNAME}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - CHAIN=${BITCOIN_NETWORK}
      - HTTP_LISTEN=0.0.0.0:${TITAN_HTTP_PORT}
      - TCP_ADDRESS=0.0.0.0:${TITAN_TCP_PORT}
    volumes:
      - "titan-data:/home/titan/data"

  bitcoind:
    image: bitcoin/bitcoin
    ports:
      - 0.0.0.0:${BITCOIN_RPC_PORT}:${BITCOIN_RPC_PORT}
    volumes:
      - "btcd-data:/var/lib/bitcoin-core"
    networks:
      titan-network:
        ipv4_address: 172.28.0.3
    command: |
      -${BITCOIN_NETWORK}
      -rpcallowip=0.0.0.0/0
      -datadir=/var/lib/bitcoin-core
      -rpcbind=bitcoind
      -rpcuser=${BITCOIN_RPC_USERNAME}
      -rpcpassword=${BITCOIN_RPC_PASSWORD}
      -fallbackfee=0.00000001
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-${BITCOIN_NETWORK}",
          "-rpcconnect=bitcoind",
          "-rpcport=${BITCOIN_RPC_PORT}",
          "-rpcuser=${BITCOIN_RPC_USERNAME}",
          "-rpcpassword=${BITCOIN_RPC_PASSWORD}",
          "getblockchaininfo",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  titan-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  titan-data:
  btcd-data: